version: '3'

# Define all the services
services:
  # Archive frontend
  archive-browser:
    build: ./archive-browser
    environment:
      - DRIVE_BASE_URL=${DRIVE_BASE_URL}
      - ES_BACKEND_URL=http://elastic:9200
      - ENABLE_SIGN_URLS=false
    # ports:
    #   - 3000:3000
    networks:
      - ragtag-archive

  # Elasticsearch database
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200
    networks:
      - ragtag-archive

  # Nginx file server
  nginx:
    image: nginx:stable
    volumes:
      # TODO: update mount point to where your files will be stored
      - ${DATA_DIRECTORY}:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT}:80
    networks:
      - ragtag-archive

  ytdlp:
    build: ./yt-dlp
    volumes:
      - ${DATA_DIRECTORY}:/data
      - ./channels.txt:/config/channels.txt
      - ${APPDATA_DIRECTORY}/ytdlp:/appdata
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - ES_BACKEND_URL=http://elastic:9200
      - DATA_DIRECTORY=${DATA_DIRECTORY}
      - YTDLP_ARGS=${YTDLP_ARGS}
      - CRON_SCHEDULE=${YTDLP_SCHEDULE}
      - RUN_ON_STARTUP=${YTDLP_RUN_ON_STARTUP}
    networks:
      - ragtag-archive

volumes:
  esdata:
    driver: local

networks:
  ragtag-archive:
    driver: bridge
